name: C:\Users\Windows\anaconda3\envs\cl_sster_env\envs\llm_openai
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=hcfcfb64_5
  - ca-certificates=2025.11.12=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.8.1=py312h53d5487_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - ipykernel=6.29.3=pyha63f2e9_0
  - ipython=8.24.0=pyh7428d3b_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h2e8e312_0
  - krb5=1.21.2=heb0366b_0
  - libblas=3.11.0=2_h0adab6e_openblas
  - libcblas=3.11.0=2_h2a8eebe_openblas
  - libexpat=2.6.2=h63175ca_0
  - libffi=3.4.2=h8ffe710_5
  - liblapack=3.11.0=2_hd232482_openblas
  - libopenblas=0.3.30=hf885159_2
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.45.3=hcfcfb64_0
  - libzlib=1.2.13=hcfcfb64_5
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=2.2.6=py312h3150e54_0
  - openssl=3.3.0=h2466b09_1
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.3.0=py312h72972c8_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py312he70551f_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.12.3=h2628c8c_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pywin32=306=py312h53d5487_2
  - pyzmq=26.0.3=py312hd7027bb_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - tornado=6.4=py312he70551f_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.3=ha32ba9b_20
  - vc14_runtime=14.38.33135=h835141b_20
  - vs2015_runtime=14.38.33135=h22015db_20
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h8d14728_0
  - zeromq=4.3.5=he1f189c_4
  - zipp=3.17.0=pyhd8ed1ab_0
  - pip:
      - adjusttext==1.3.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - attrs==24.2.0
      - certifi==2024.7.4
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - datasets==3.0.2
      - decorator==4.4.2
      - deprecated==1.2.18
      - dill==0.3.8
      - distro==1.9.0
      - fastjsonschema==2.21.1
      - filelock==3.16.1
      - filterpy==1.4.5
      - fonttools==4.53.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - future==1.0.0
      - graphtools==1.5.3
      - h11==0.14.0
      - h5py==3.11.0
      - hmmlearn==0.3.2
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.26.2
      - hurst==0.0.5
      - idna==3.7
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - iniconfig==2.0.0
      - jinja2==3.1.3
      - jiter==0.9.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.5
      - kmapper==2.1.0
      - llvmlite==0.43.0
      - lxml==5.3.0
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - moviepy==1.0.3
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - narwhals==1.31.0
      - nbformat==5.10.4
      - networkx==3.2.1
      - nibabel==5.3.2
      - nilearn==0.10.4
      - numba==0.60.0
      - openai==1.69.0
      - patsy==1.0.1
      - phate==1.0.11
      - pillow==10.4.0
      - plotly==6.0.1
      - pluggy==1.5.0
      - proglog==0.1.10
      - propcache==0.2.0
      - pyarrow==18.0.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyfftw==0.15.0
      - pygsp==0.5.1
      - pynndescent==0.5.13
      - pyparsing==3.1.2
      - pytest==8.3.3
      - pytz==2024.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.3
      - rpds-py==0.24.0
      - s-gd2==1.8.1
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - scprep==1.2.3
      - seaborn==0.13.2
      - setuptools==80.9.0
      - sniffio==1.3.1
      - sporco==0.2.1
      - statsmodels==0.14.4
      - stumpy==1.13.0
      - sympy==1.13.1
      - tasklogger==1.2.0
      - threadpoolctl==3.5.0
      - torch==2.5.1+cu124
      - torchaudio==2.5.1+cu124
      - torchnmf==0.3.5
      - torchvision==0.20.1+cu124
      - tphate==1.1
      - tqdm==4.66.4
      - tzdata==2024.1
      - umap-learn==0.5.7
      - urllib3==2.2.2
      - wordcloud==1.9.4
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yarl==1.17.1
prefix: C:\Users\Windows\anaconda3\envs\cl_sster_env\envs\llm_openai
